# Generated by Django 4.1.7 on 2023-03-17 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherDirectoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teachersinformation',
            table='teachers_information',
        ),
    ]
